#ifndef GVIZARD_COLORS_SVG_HPP_
#define GVIZARD_COLORS_SVG_HPP_

#include <gvizard/utils.hpp>

#include <gvizard/colors/general.hpp>
#include <gvizard/colors/rgb.hpp>

namespace gvizard::colors {

enum class SVGColorEnum : uint16_t {
  aliceblue,
  antiquewhite,
  aqua,
  aquamarine,
  azure,
  beige,
  bisque,
  black,
  blanchedalmond,
  blue,
  blueviolet,
  brown,
  burlywood,
  cadetblue,
  chartreuse,
  chocolate,
  coral,
  cornflowerblue,
  cornsilk,
  crimson,
  cyan,
  darkblue,
  darkcyan,
  darkgoldenrod,
  darkgray,
  darkgreen,
  darkgrey,
  darkkhaki,
  darkmagenta,
  darkolivegreen,
  darkorange,
  darkorchid,
  darkred,
  darksalmon,
  darkseagreen,
  darkslateblue,
  darkslategray,
  darkslategrey,
  darkturquoise,
  darkviolet,
  deeppink,
  deepskyblue,
  dimgray,
  dimgrey,
  dodgerblue,
  firebrick,
  floralwhite,
  forestgreen,
  fuchsia,
  gainsboro,
  ghostwhite,
  gold,
  goldenrod,
  gray,
  green,
  greenyellow,
  grey,
  honeydew,
  hotpink,
  indianred,
  indigo,
  ivory,
  khaki,
  lavender,
  lavenderblush,
  lawngreen,
  lemonchiffon,
  lightblue,
  lightcoral,
  lightcyan,
  lightgoldenrodyellow,
  lightgray,
  lightgreen,
  lightgrey,
  lightpink,
  lightsalmon,
  lightseagreen,
  lightskyblue,
  lightslategray,
  lightslategrey,
  lightsteelblue,
  lightyellow,
  lime,
  limegreen,
  linen,
  magenta,
  maroon,
  mediumaquamarine,
  mediumblue,
  mediumorchid,
  mediumpurple,
  mediumseagreen,
  mediumslateblue,
  mediumspringgreen,
  mediumturquoise,
  mediumvioletred,
  midnightblue,
  mintcream,
  mistyrose,
  moccasin,
  navajowhite,
  navy,
  oldlace,
  olive,
  olivedrab,
  orange,
  orangered,
  orchid,
  palegoldenrod,
  palegreen,
  paleturquoise,
  palevioletred,
  papayawhip,
  peachpuff,
  peru,
  pink,
  plum,
  powderblue,
  purple,
  red,
  rosybrown,
  royalblue,
  saddlebrown,
  salmon,
  sandybrown,
  seagreen,
  seashell,
  sienna,
  silver,
  skyblue,
  slateblue,
  slategray,
  slategrey,
  snow,
  springgreen,
  steelblue,
  tan,
  teal,
  thistle,
  tomato,
  turquoise,
  violet,
  wheat,
  white,
  whitesmoke,
  yellow,
  yellowgreen
};  // enum class SVGColorEnum    
      
class SVGColor final {         
  SVGColorEnum    index_;           
  SchemeColor<RGB> color_;             
               
 public:                  
  constexpr SVGColor(SVGColorEnum index)                    
    : index_(index), color_(list[uint16_t(index)])               
  {}                       
                         
  constexpr SVGColorEnum     get_enum()  const noexcept { return index_; }
  constexpr SchemeColor<RGB> get_color() const noexcept { return color_; }

  constexpr operator SchemeColor<RGB>() const noexcept { return color_; }

  constexpr bool operator==(const SVGColor& other) const noexcept
  {
    return get_enum() == other.get_enum();
  }

  constexpr bool operator!=(const SVGColor& other) const noexcept
  {
    return get_enum() != other.get_enum();
  }
                             
  constexpr static SchemeColor<RGB> list[] = {                      
    { "aliceblue"            , RGB{ 240,248,255 }, SchemeEnum::SVG },
    { "antiquewhite"         , RGB{ 250,235,215 }, SchemeEnum::SVG },
    { "aqua"                 , RGB{ 0  ,255,255 }, SchemeEnum::SVG },
    { "aquamarine"           , RGB{ 127,255,212 }, SchemeEnum::SVG },
    { "azure"                , RGB{ 240,255,255 }, SchemeEnum::SVG },
    { "beige"                , RGB{ 245,245,220 }, SchemeEnum::SVG },
    { "bisque"               , RGB{ 255,228,196 }, SchemeEnum::SVG },
    { "black"                , RGB{ 0  ,0  ,0   }, SchemeEnum::SVG },
    { "blanchedalmond"       , RGB{ 255,235,205 }, SchemeEnum::SVG },
    { "blue"                 , RGB{ 0  ,0  ,255 }, SchemeEnum::SVG },
    { "blueviolet"           , RGB{ 138,43 ,226 }, SchemeEnum::SVG },
    { "brown"                , RGB{ 165,42 ,42  }, SchemeEnum::SVG },
    { "burlywood"            , RGB{ 222,184,135 }, SchemeEnum::SVG },
    { "cadetblue"            , RGB{ 95 ,158,160 }, SchemeEnum::SVG },
    { "chartreuse"           , RGB{ 127,255,0   }, SchemeEnum::SVG },
    { "chocolate"            , RGB{ 210,105,30  }, SchemeEnum::SVG },
    { "coral"                , RGB{ 255,127,80  }, SchemeEnum::SVG },
    { "cornflowerblue"       , RGB{ 100,149,237 }, SchemeEnum::SVG },
    { "cornsilk"             , RGB{ 255,248,220 }, SchemeEnum::SVG },
    { "crimson"              , RGB{ 220,20 ,60  }, SchemeEnum::SVG },
    { "cyan"                 , RGB{ 0  ,255,255 }, SchemeEnum::SVG },
    { "darkblue"             , RGB{ 0  ,0  ,139 }, SchemeEnum::SVG },
    { "darkcyan"             , RGB{ 0  ,139,139 }, SchemeEnum::SVG },
    { "darkgoldenrod"        , RGB{ 184,134,11  }, SchemeEnum::SVG },
    { "darkgray"             , RGB{ 169,169,169 }, SchemeEnum::SVG },
    { "darkgreen"            , RGB{ 0  ,100,0   }, SchemeEnum::SVG },
    { "darkgrey"             , RGB{ 169,169,169 }, SchemeEnum::SVG },
    { "darkkhaki"            , RGB{ 189,183,107 }, SchemeEnum::SVG },
    { "darkmagenta"          , RGB{ 139,0  ,139 }, SchemeEnum::SVG },
    { "darkolivegreen"       , RGB{ 85 ,107,47  }, SchemeEnum::SVG },
    { "darkorange"           , RGB{ 255,140,0   }, SchemeEnum::SVG },
    { "darkorchid"           , RGB{ 153,50 ,204 }, SchemeEnum::SVG },
    { "darkred"              , RGB{ 139,0  ,0   }, SchemeEnum::SVG },
    { "darksalmon"           , RGB{ 233,150,122 }, SchemeEnum::SVG },
    { "darkseagreen"         , RGB{ 143,188,143 }, SchemeEnum::SVG },
    { "darkslateblue"        , RGB{ 72 ,61 ,139 }, SchemeEnum::SVG },
    { "darkslategray"        , RGB{ 47 ,79 ,79  }, SchemeEnum::SVG },
    { "darkslategrey"        , RGB{ 47 ,79 ,79  }, SchemeEnum::SVG },
    { "darkturquoise"        , RGB{ 0  ,206,209 }, SchemeEnum::SVG },
    { "darkviolet"           , RGB{ 148,0  ,211 }, SchemeEnum::SVG },
    { "deeppink"             , RGB{ 255,20 ,147 }, SchemeEnum::SVG },
    { "deepskyblue"          , RGB{ 0  ,191,255 }, SchemeEnum::SVG },
    { "dimgray"              , RGB{ 105,105,105 }, SchemeEnum::SVG },
    { "dimgrey"              , RGB{ 105,105,105 }, SchemeEnum::SVG },
    { "dodgerblue"           , RGB{ 30 ,144,255 }, SchemeEnum::SVG },
    { "firebrick"            , RGB{ 178,34 ,34  }, SchemeEnum::SVG },
    { "floralwhite"          , RGB{ 255,250,240 }, SchemeEnum::SVG },
    { "forestgreen"          , RGB{ 34 ,139,34  }, SchemeEnum::SVG },
    { "fuchsia"              , RGB{ 255,0  ,255 }, SchemeEnum::SVG },
    { "gainsboro"            , RGB{ 220,220,220 }, SchemeEnum::SVG },
    { "ghostwhite"           , RGB{ 248,248,255 }, SchemeEnum::SVG },
    { "gold"                 , RGB{ 255,215,0   }, SchemeEnum::SVG },
    { "goldenrod"            , RGB{ 218,165,32  }, SchemeEnum::SVG },
    { "gray"                 , RGB{ 128,128,128 }, SchemeEnum::SVG },
    { "green"                , RGB{ 0  ,128,0   }, SchemeEnum::SVG },
    { "greenyellow"          , RGB{ 173,255,47  }, SchemeEnum::SVG },
    { "grey"                 , RGB{ 128,128,128 }, SchemeEnum::SVG },
    { "honeydew"             , RGB{ 240,255,240 }, SchemeEnum::SVG },
    { "hotpink"              , RGB{ 255,105,180 }, SchemeEnum::SVG },
    { "indianred"            , RGB{ 205,92 ,92  }, SchemeEnum::SVG },
    { "indigo"               , RGB{ 75 ,0  ,130 }, SchemeEnum::SVG },
    { "ivory"                , RGB{ 255,255,240 }, SchemeEnum::SVG },
    { "khaki"                , RGB{ 240,230,140 }, SchemeEnum::SVG },
    { "lavender"             , RGB{ 230,230,250 }, SchemeEnum::SVG },
    { "lavenderblush"        , RGB{ 255,240,245 }, SchemeEnum::SVG },
    { "lawngreen"            , RGB{ 124,252,0   }, SchemeEnum::SVG },
    { "lemonchiffon"         , RGB{ 255,250,205 }, SchemeEnum::SVG },
    { "lightblue"            , RGB{ 173,216,230 }, SchemeEnum::SVG },
    { "lightcoral"           , RGB{ 240,128,128 }, SchemeEnum::SVG },
    { "lightcyan"            , RGB{ 224,255,255 }, SchemeEnum::SVG },
    { "lightgoldenrodyellow" , RGB{ 250,250,210 }, SchemeEnum::SVG },
    { "lightgray"            , RGB{ 211,211,211 }, SchemeEnum::SVG },
    { "lightgreen"           , RGB{ 144,238,144 }, SchemeEnum::SVG },
    { "lightgrey"            , RGB{ 211,211,211 }, SchemeEnum::SVG },
    { "lightpink"            , RGB{ 255,182,193 }, SchemeEnum::SVG },
    { "lightsalmon"          , RGB{ 255,160,122 }, SchemeEnum::SVG },
    { "lightseagreen"        , RGB{ 32 ,178,170 }, SchemeEnum::SVG },
    { "lightskyblue"         , RGB{ 135,206,250 }, SchemeEnum::SVG },
    { "lightslategray"       , RGB{ 119,136,153 }, SchemeEnum::SVG },
    { "lightslategrey"       , RGB{ 119,136,153 }, SchemeEnum::SVG },
    { "lightsteelblue"       , RGB{ 176,196,222 }, SchemeEnum::SVG },
    { "lightyellow"          , RGB{ 255,255,224 }, SchemeEnum::SVG },
    { "lime"                 , RGB{ 0  ,255,0   }, SchemeEnum::SVG },
    { "limegreen"            , RGB{ 50 ,205,50  }, SchemeEnum::SVG },
    { "linen"                , RGB{ 250,240,230 }, SchemeEnum::SVG },
    { "magenta"              , RGB{ 255,0  ,255 }, SchemeEnum::SVG },
    { "maroon"               , RGB{ 128,0  ,0   }, SchemeEnum::SVG },
    { "mediumaquamarine"     , RGB{ 102,205,170 }, SchemeEnum::SVG },
    { "mediumblue"           , RGB{ 0  ,0  ,205 }, SchemeEnum::SVG },
    { "mediumorchid"         , RGB{ 186,85 ,211 }, SchemeEnum::SVG },
    { "mediumpurple"         , RGB{ 147,112,219 }, SchemeEnum::SVG },
    { "mediumseagreen"       , RGB{ 60 ,179,113 }, SchemeEnum::SVG },
    { "mediumslateblue"      , RGB{ 123,104,238 }, SchemeEnum::SVG },
    { "mediumspringgreen"    , RGB{ 0  ,250,154 }, SchemeEnum::SVG },
    { "mediumturquoise"      , RGB{ 72 ,209,204 }, SchemeEnum::SVG },
    { "mediumvioletred"      , RGB{ 199,21 ,133 }, SchemeEnum::SVG },
    { "midnightblue"         , RGB{ 25 ,25 ,112 }, SchemeEnum::SVG },
    { "mintcream"            , RGB{ 245,255,250 }, SchemeEnum::SVG },
    { "mistyrose"            , RGB{ 255,228,225 }, SchemeEnum::SVG },
    { "moccasin"             , RGB{ 255,228,181 }, SchemeEnum::SVG },
    { "navajowhite"          , RGB{ 255,222,173 }, SchemeEnum::SVG },
    { "navy"                 , RGB{ 0  ,0  ,128 }, SchemeEnum::SVG },
    { "oldlace"              , RGB{ 253,245,230 }, SchemeEnum::SVG },
    { "olive"                , RGB{ 128,128,0   }, SchemeEnum::SVG },
    { "olivedrab"            , RGB{ 107,142,35  }, SchemeEnum::SVG },
    { "orange"               , RGB{ 255,165,0   }, SchemeEnum::SVG },
    { "orangered"            , RGB{ 255,69 ,0   }, SchemeEnum::SVG },
    { "orchid"               , RGB{ 218,112,214 }, SchemeEnum::SVG },
    { "palegoldenrod"        , RGB{ 238,232,170 }, SchemeEnum::SVG },
    { "palegreen"            , RGB{ 152,251,152 }, SchemeEnum::SVG },
    { "paleturquoise"        , RGB{ 175,238,238 }, SchemeEnum::SVG },
    { "palevioletred"        , RGB{ 219,112,147 }, SchemeEnum::SVG },
    { "papayawhip"           , RGB{ 255,239,213 }, SchemeEnum::SVG },
    { "peachpuff"            , RGB{ 255,218,185 }, SchemeEnum::SVG },
    { "peru"                 , RGB{ 205,133,63  }, SchemeEnum::SVG },
    { "pink"                 , RGB{ 255,192,203 }, SchemeEnum::SVG },
    { "plum"                 , RGB{ 221,160,221 }, SchemeEnum::SVG },
    { "powderblue"           , RGB{ 176,224,230 }, SchemeEnum::SVG },
    { "purple"               , RGB{ 128,0  ,128 }, SchemeEnum::SVG },
    { "red"                  , RGB{ 255,0  ,0   }, SchemeEnum::SVG },
    { "rosybrown"            , RGB{ 188,143,143 }, SchemeEnum::SVG },
    { "royalblue"            , RGB{ 65 ,105,225 }, SchemeEnum::SVG },
    { "saddlebrown"          , RGB{ 139,69 ,19  }, SchemeEnum::SVG },
    { "salmon"               , RGB{ 250,128,114 }, SchemeEnum::SVG },
    { "sandybrown"           , RGB{ 244,164,96  }, SchemeEnum::SVG },
    { "seagreen"             , RGB{ 46 ,139,87  }, SchemeEnum::SVG },
    { "seashell"             , RGB{ 255,245,238 }, SchemeEnum::SVG },
    { "sienna"               , RGB{ 160,82 ,45  }, SchemeEnum::SVG },
    { "silver"               , RGB{ 192,192,192 }, SchemeEnum::SVG },
    { "skyblue"              , RGB{ 135,206,235 }, SchemeEnum::SVG },
    { "slateblue"            , RGB{ 106,90 ,205 }, SchemeEnum::SVG },
    { "slategray"            , RGB{ 112,128,144 }, SchemeEnum::SVG },
    { "slategrey"            , RGB{ 112,128,144 }, SchemeEnum::SVG },
    { "snow"                 , RGB{ 255,250,250 }, SchemeEnum::SVG },
    { "springgreen"          , RGB{ 0  ,255,127 }, SchemeEnum::SVG },
    { "steelblue"            , RGB{ 70 ,130,180 }, SchemeEnum::SVG },
    { "tan"                  , RGB{ 210,180,140 }, SchemeEnum::SVG },
    { "teal"                 , RGB{ 0  ,128,128 }, SchemeEnum::SVG },
    { "thistle"              , RGB{ 216,191,216 }, SchemeEnum::SVG },
    { "tomato"               , RGB{ 255,99 ,71  }, SchemeEnum::SVG },
    { "turquoise"            , RGB{ 64 ,224,208 }, SchemeEnum::SVG },
    { "violet"               , RGB{ 238,130,238 }, SchemeEnum::SVG },
    { "wheat"                , RGB{ 245,222,179 }, SchemeEnum::SVG },
    { "white"                , RGB{ 255,255,255 }, SchemeEnum::SVG },
    { "whitesmoke"           , RGB{ 245,245,245 }, SchemeEnum::SVG },
    { "yellow"               , RGB{ 255,255,0   }, SchemeEnum::SVG },
    { "yellowgreen"          , RGB{ 154,205,50  }, SchemeEnum::SVG }
  };
};  // struct SVGColor

}  // namespace gvizard::colors

#endif  // GVIZARD_COLORS_SVG_HPP_
