#ifndef GVIZARD_ATTRS_HPP_
#define GVIZARD_ATTRS_HPP_

#include <gvizard/attrs/area.hpp>
#include <gvizard/attrs/arrow_related.hpp>
#include <gvizard/attrs/bgcolor.hpp>
#include <gvizard/attrs/boundingbox.hpp>
#include <gvizard/attrs/center.hpp>
#include <gvizard/attrs/charset.hpp>
#include <gvizard/attrs/clazz.hpp>
#include <gvizard/attrs/clusterrank.hpp>
#include <gvizard/attrs/color.hpp>
#include <gvizard/attrs/colorscheme.hpp>
#include <gvizard/attrs/comment.hpp>
#include <gvizard/attrs/compound.hpp>
#include <gvizard/attrs/concentrate.hpp>
#include <gvizard/attrs/constraint.hpp>
#include <gvizard/attrs/damping.hpp>
#include <gvizard/attrs/decorate.hpp>
#include <gvizard/attrs/defaultdist.hpp>
#include <gvizard/attrs/dim.hpp>
#include <gvizard/attrs/dimen.hpp>
#include <gvizard/attrs/dir.hpp>
#include <gvizard/attrs/distortion.hpp>
#include <gvizard/attrs/dpi.hpp>
#include <gvizard/attrs/edge_related.hpp>
#include <gvizard/attrs/epsilon.hpp>
#include <gvizard/attrs/esep.hpp>
#include <gvizard/attrs/fillcolor.hpp>
#include <gvizard/attrs/fixedsize.hpp>
#include <gvizard/attrs/font_related.hpp>
#include <gvizard/attrs/forcelabels.hpp>
#include <gvizard/attrs/gradientangle.hpp>
#include <gvizard/attrs/group.hpp>
#include <gvizard/attrs/head_related.hpp>
#include <gvizard/attrs/height.hpp>
#include <gvizard/attrs/href.hpp>
#include <gvizard/attrs/id.hpp>
#include <gvizard/attrs/image_related.hpp>
#include <gvizard/attrs/inputscale.hpp>
#include <gvizard/attrs/k.hpp>
#include <gvizard/attrs/label_related.hpp>
#include <gvizard/attrs/landscape.hpp>
#include <gvizard/attrs/layer_related.hpp>
#include <gvizard/attrs/layout.hpp>
#include <gvizard/attrs/len.hpp>
#include <gvizard/attrs/level_related.hpp>
#include <gvizard/attrs/logical_related.hpp>
#include <gvizard/attrs/margin.hpp>
#include <gvizard/attrs/maxiter.hpp>
#include <gvizard/attrs/mclimit.hpp>
#include <gvizard/attrs/mindist.hpp>
#include <gvizard/attrs/minlen.hpp>
#include <gvizard/attrs/mode.hpp>
#include <gvizard/attrs/model.hpp>
#include <gvizard/attrs/mosek.hpp>
#include <gvizard/attrs/newrank.hpp>
#include <gvizard/attrs/nodesep.hpp>
#include <gvizard/attrs/nojustify.hpp>
#include <gvizard/attrs/normalize.hpp>
#include <gvizard/attrs/notranslate.hpp>
#include <gvizard/attrs/nslimit.hpp>
#include <gvizard/attrs/nslimit1.hpp>
#include <gvizard/attrs/ordering.hpp>
#include <gvizard/attrs/orientation.hpp>
#include <gvizard/attrs/outputorder.hpp>
#include <gvizard/attrs/overlap_related.hpp>
#include <gvizard/attrs/pack.hpp>
#include <gvizard/attrs/packmode.hpp>
#include <gvizard/attrs/pad.hpp>
#include <gvizard/attrs/page.hpp>
#include <gvizard/attrs/pagedir.hpp>
#include <gvizard/attrs/pencolor.hpp>
#include <gvizard/attrs/penwidth.hpp>
#include <gvizard/attrs/peripheries.hpp>
#include <gvizard/attrs/pin.hpp>
#include <gvizard/attrs/pos.hpp>
#include <gvizard/attrs/quadtree.hpp>
#include <gvizard/attrs/quantum.hpp>
#include <gvizard/attrs/rank.hpp>
#include <gvizard/attrs/rankdir.hpp>
#include <gvizard/attrs/ranksep.hpp>
#include <gvizard/attrs/ratio.hpp>
#include <gvizard/attrs/rects.hpp>
#include <gvizard/attrs/regular.hpp>
#include <gvizard/attrs/remincross.hpp>
#include <gvizard/attrs/repulsiveforce.hpp>
#include <gvizard/attrs/resolution.hpp>
#include <gvizard/attrs/root.hpp>
#include <gvizard/attrs/rotate.hpp>
#include <gvizard/attrs/rotation.hpp>
#include <gvizard/attrs/samehead.hpp>
#include <gvizard/attrs/sametail.hpp>
#include <gvizard/attrs/samplepoints.hpp>
#include <gvizard/attrs/scale.hpp>
#include <gvizard/attrs/searchsize.hpp>
#include <gvizard/attrs/sep.hpp>
#include <gvizard/attrs/shadowboxes.hpp>
#include <gvizard/attrs/shape.hpp>
#include <gvizard/attrs/shapefile.hpp>
#include <gvizard/attrs/sides.hpp>
#include <gvizard/attrs/size.hpp>
#include <gvizard/attrs/skew.hpp>
#include <gvizard/attrs/smoothing.hpp>
#include <gvizard/attrs/sortv.hpp>
#include <gvizard/attrs/splines.hpp>
#include <gvizard/attrs/start.hpp>
#include <gvizard/attrs/style.hpp>
#include <gvizard/attrs/stylesheet.hpp>
#include <gvizard/attrs/tail_related.hpp>
#include <gvizard/attrs/target.hpp>
#include <gvizard/attrs/tooltip.hpp>
#include <gvizard/attrs/truecolor.hpp>
#include <gvizard/attrs/url.hpp>
#include <gvizard/attrs/vertices.hpp>
#include <gvizard/attrs/viewport.hpp>
#include <gvizard/attrs/voro_margin.hpp>
#include <gvizard/attrs/weight.hpp>
#include <gvizard/attrs/width.hpp>
#include <gvizard/attrs/xdotversion.hpp>
#include <gvizard/attrs/xlabel.hpp>
#include <gvizard/attrs/z.hpp>

#endif  // GVIZARD_ATTRS_HPP_
